component.icon.path = ./res/img/ico/componentIcon.png
component.title = titulo

component.margin.insets.top = 10
component.margin.insets.left = 10
component.margin.insets.bottom = 10
component.margin.insets.right = 10
